services:
  mes-api:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - 5533:1433
    volumes:
      - store-vol:/var/opt/mssql
volumes:
  store-vol:
    external: true